workflows:
  flutter_ci:
    name: Flutter CI
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
        - pull_request
        - manual
      branch_patterns:
        - pattern: master
          include: true
          source: true
        - pattern: main
          include: true
          source: true
    environment:
      flutter: stable
    scripts:
      - name: Flutter version
        script: flutter --version
      - name: Get dependencies
        script: flutter pub get
      - name: Generate localizations
        script: flutter gen-l10n
      - name: Lint (custom_lint)
        script: dart run custom_lint
      - name: Analyze
        script: flutter analyze
      - name: Run tests
        # Use compact reporter and disable ANSI to make logs stable in CI
        script: flutter test --no-color -r compact
    cache:
      - key: "pub-cache"
        paths:
          - ~/.pub-cache
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/ios/ipa/*.ipa
      - build/macos/Build/Products/**
