name: app_lints
version: 0.1.0
publish_to: 'none'
description: Custom lint rules for the musice app.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^8.0.0
  custom_lint_builder: ^0.8.1

dev_dependencies:
  custom_lint: ^0.8.1
