name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Generate localizations
        run: flutter gen-l10n

      - name: Run custom lint (fail on violations)
        run: dart run custom_lint

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test -r compact
